#ifndef GLOBAL_CONSTANTS_H
#define GLOBAL_CONSTANTS_H

#define BLANK_IMG_WIDTH 500
#define BLANK_IMG_HEIGHT 375
#define WIDTH_STEP 25
#define HEIGHT_STEP 25
#define VEC_SIZE ((BLANK_IMG_WIDTH / WIDTH_STEP) * (BLANK_IMG_HEIGHT / HEIGHT_STEP))
#define MAX_CLASS_NAME_LENGTH 100

#endif // GLOBAL_CONSTANTS_H
